apiVersion: v1
description: Polyaxon in-cluster NFS provisioner to simplify the creation of ReadWriteMany and ReadOnlyMany volumes.
name: polyaxon
version: 0.4.0
keywords:
  - deep learning
  - a.i.
  - machine learning
  - infrastructure
  - nfs
  - storage
sources:
  - https://github.com/polyaxon
home: https://polyaxon.com
icon: https://polyaxon.com/img/icon.png
maintainers:
  - name: Polyaxon
    email: contact@polyaxon.com
    url: polyaxon.com
